name: Aktualizacja formuły Homebrew

on:
  release:
    types: [released]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repozytorium tapu
        uses: actions/checkout@v4

      - name: Aktualizuj formułę Homebrew
        uses: dawidd6/action-homebrew-bump-formula@v4
        with:
          # Token personalny z uprawnieniami public_repo; ustaw w sekcji Secrets o nazwie HOMEBREW_BUMP_TOKEN
          token: ${{ secrets.WITX_PAT_TOKEN }}
          user_name: "witx98"
          user_email: "witxdev@gmail.com"
          # Nazwa repozytorium tapu, np. twoj-login/homebrew-logchange
          tap: witx98/homebrew-test-logchange
          # Nazwa formuły – plik logchange.rb
          no_fork: false
          formula: logchange
          # Automatycznie pobiera tag z release (np. "1.16.8")
          tag: ${{ github.ref_name }}
